"""empty message

Revision ID: 249d8b113727
Revises: 
Create Date: 2022-09-21 11:57:34.528691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249d8b113727'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=80), nullable=False),
    sa.Column('image', sa.VARCHAR(length=255), nullable=False),
    sa.Column('qty_stock', sa.INTEGER(), nullable=True),
    sa.Column('prix_unitaire', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('image')
    )
    # ### end Alembic commands ###
