"""empty message

Revision ID: 6fc485189a34
Revises: 249d8b113727
Create Date: 2022-09-22 16:23:19.102000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc485189a34'
down_revision = '249d8b113727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facture', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'facture', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facture', type_='foreignkey')
    op.drop_column('facture', 'client_id')
    # ### end Alembic commands ###
